### ISSUE TITLE
AttributeError: 'Variant' object has no attribute 'is_insertion'

### ISSUE THREAD

**Issue by JPFinnigan** [hammerlab/isovar#16]
Run with:
```
isovar-protein-sequences.py \
--vcf ~/Desktop/WD/Results/WES/Tumor_B16.F10_0810/ISMMS/VCF/Strelka/results/passed.somatic.snvs.indels.vcf \
--bam ~/Desktop/WD/Results/RNA/Tumor_B16.F10/ISMMS/Tumor_B16.F10_0810.131B/BAM/HISAT2/Tumor_B16.F10_0810.131B.HISAT2.sorted.bam \
--genome mm10 \
--min-reads 2 \
--protein-sequence-length 30 \
--output ~/Desktop/isovar-results.csv
```

Output: 
```
Namespace(bam='/Users/johnfinnigan/Desktop/WD/Results/RNA/Tumor_B16.F10/ISMMS/Tumor_B16.F10_0810.131B/BAM/HISAT2/Tumor_B16.F10_0810.131B.HISAT2.sorted.bam', genome='mm10', max_reference_transcript_mismatches=2, max_sequences_per_variant=1, min_mapping_quality=0, min_reads=2, min_transcript_prefix_length=10, output='/Users/johnfinnigan/Desktop/isovar-results.csv', protein_sequence_length=30, vcf='/Users/johnfinnigan/Desktop/WD/Results/WES/Tumor_B16.F10_0810/ISMMS/VCF/Strelka/results/passed.somatic.snvs.indels.vcf')
INFO:root:Gathering reads for Variant(contig=1, start=4346510, ref=., alt=T, reference_name=GRCm38)
INFO:root:Gathering variant reads for variant Variant(contig=1, start=4346510, ref=., alt=T, reference_name=GRCm38) (chromosome=1)
INFO:root:Found 0 reads at locus overlapping Variant(contig=1, start=4346510, ref=., alt=T, reference_name=GRCm38)
INFO:root:Found 0 VariantReads for variant Variant(contig=1, start=4346510, ref=., alt=T, reference_name=GRCm38)
INFO:root:Looking at 46nt before and 46nt after variant Variant(contig=1, start=4346510, ref=., alt=T, reference_name=GRCm38)
INFO:root:Skipping variant Variant(contig=1, start=4346510, ref=., alt=T, reference_name=GRCm38), no cDNA sequences detected
INFO:root:Gathering reads for Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Gathering variant reads for variant Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38) (chromosome=1)
INFO:root:Found 1 reads at locus overlapping Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Found 1 VariantReads for variant Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Looking at 46nt before and 46nt after variant Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Dropped 1/1 variant sequences
INFO:root:Skipping variant Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38), no cDNA sequences detected
INFO:root:Gathering reads for Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
INFO:root:Gathering variant reads for variant Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38) (chromosome=1)
INFO:root:Found 10 reads at locus overlapping Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
INFO:root:Found 10 VariantReads for variant Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
INFO:root:Looking at 46nt before and 46nt after variant Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
INFO:root:Dropped 6/7 variant sequences
INFO:root:Predicted 4 effects for variant Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
INFO:root:Keeping 4/4 non-synonymous coding effects for Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
INFO:root:Keeping 4/4 effects with predictable AA sequences for Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/isovar-protein-sequences.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/script/isovar-protein-sequences.py", line 115, in <module>
    min_mapping_quality=args.min_mapping_quality)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/protein_sequence.py", line 250, in variants_to_protein_sequences_dataframe
    for (variant, protein_sequences) in variants_to_protein_sequences(*args, **kwargs):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/protein_sequence.py", line 194, in variants_to_protein_sequences
    min_mapping_quality=min_mapping_quality):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/translation.py", line 614, in translate_variants
    transcript_id_whitelist=transcript_id_whitelist)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/reference_context.py", line 367, in reference_contexts_for_variant
    context_size=context_size)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/reference_context.py", line 253, in sequence_key_with_reading_frame_for_variant_on_transcript
    context_size=context_size)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/reference_context.py", line 147, in sequence_key_for_variant_on_transcript
    transcript=transcript)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/variant_helpers.py", line 148, in interbase_range_affected_by_variant_on_transcript
    if variant.is_insertion:
AttributeError: 'Variant' object has no attribute 'is_insertion'
```

I ran this with both the MuTect and Strelka .vcf, and both RNASeq datasets. Quickly perusing the locus in both RNASeq datasets, would indicate that this is likely a FP. Similarly, running w/ the B16.F1 data fails w/: 
```
Namespace(bam='/Users/johnfinnigan/Desktop/WD/Results/RNA/Tumor_B16.F1/Tumor_B16.F1_0821.115B/BAM/HISAT2/Tumor_B16.F1_0821.115B.HISAT2.sorted.bam', genome='mm10', max_reference_transcript_mismatches=2, max_sequences_per_variant=1, min_mapping_quality=0, min_reads=2, min_transcript_prefix_length=10, output='/Users/johnfinnigan/Desktop/isovar-results.csv', protein_sequence_length=30, vcf='/Users/johnfinnigan/Desktop/WD/Results/WES/Tumor_B16.F1_0821/ISMMS/VCF/MuTect/Tumor_B16_F1_0821.mutect.targets.pass.vcf')
INFO:root:Gathering reads for Variant(contig=1, start=3671038, ref=C, alt=T, reference_name=GRCm38)
INFO:root:Gathering variant reads for variant Variant(contig=1, start=3671038, ref=C, alt=T, reference_name=GRCm38) (chromosome=1)
INFO:root:Found 0 reads at locus overlapping Variant(contig=1, start=3671038, ref=C, alt=T, reference_name=GRCm38)
INFO:root:Found 0 VariantReads for variant Variant(contig=1, start=3671038, ref=C, alt=T, reference_name=GRCm38)
INFO:root:Looking at 46nt before and 46nt after variant Variant(contig=1, start=3671038, ref=C, alt=T, reference_name=GRCm38)
INFO:root:Skipping variant Variant(contig=1, start=3671038, ref=C, alt=T, reference_name=GRCm38), no cDNA sequences detected
INFO:root:Gathering reads for Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Gathering variant reads for variant Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38) (chromosome=1)
INFO:root:Found 0 reads at locus overlapping Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Found 0 VariantReads for variant Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Looking at 46nt before and 46nt after variant Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Skipping variant Variant(contig=1, start=4492071, ref=G, alt=C, reference_name=GRCm38), no cDNA sequences detected
INFO:root:Gathering reads for Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
INFO:root:Gathering variant reads for variant Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38) (chromosome=1)
INFO:root:Found 7 reads at locus overlapping Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
INFO:root:Found 7 VariantReads for variant Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
INFO:root:Looking at 46nt before and 46nt after variant Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38)
INFO:root:Dropped 7/7 variant sequences
INFO:root:Skipping variant Variant(contig=1, start=4492302, ref=G, alt=T, reference_name=GRCm38), no cDNA sequences detected
INFO:root:Gathering reads for Variant(contig=1, start=4493244, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Gathering variant reads for variant Variant(contig=1, start=4493244, ref=G, alt=C, reference_name=GRCm38) (chromosome=1)
INFO:root:Found 5 reads at locus overlapping Variant(contig=1, start=4493244, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Found 5 VariantReads for variant Variant(contig=1, start=4493244, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Looking at 46nt before and 46nt after variant Variant(contig=1, start=4493244, ref=G, alt=C, reference_name=GRCm38)
INFO:root:Dropped 5/5 variant sequences
INFO:root:Skipping variant Variant(contig=1, start=4493244, ref=G, alt=C, reference_name=GRCm38), no cDNA sequences detected
INFO:root:Gathering reads for Variant(contig=1, start=5098048, ref=A, alt=C, reference_name=GRCm38)
INFO:root:Gathering variant reads for variant Variant(contig=1, start=5098048, ref=A, alt=C, reference_name=GRCm38) (chromosome=1)
INFO:root:Found 387 reads at locus overlapping Variant(contig=1, start=5098048, ref=A, alt=C, reference_name=GRCm38)
INFO:root:Found 387 VariantReads for variant Variant(contig=1, start=5098048, ref=A, alt=C, reference_name=GRCm38)
INFO:root:Looking at 46nt before and 46nt after variant Variant(contig=1, start=5098048, ref=A, alt=C, reference_name=GRCm38)
INFO:root:Dropped 106/107 variant sequences
INFO:root:Skipping transcript Transcript(id=ENSMUST00000192142, name=Atp6v1h-005, gene_id=ENSMUSG00000033793, gene_name=Atp6v1h, biotype=retained_intron, location=1:5083164-5099777) for variant Variant(contig=1, start=5098048, ref=A, alt=C, reference_name=GRCm38) because it's incomplete
INFO:root:Skipping transcript Transcript(id=ENSMUST00000194301, name=Atp6v1h-004, gene_id=ENSMUSG00000033793, gene_name=Atp6v1h, biotype=retained_intron, location=1:5083124-5145052) for variant Variant(contig=1, start=5098048, ref=A, alt=C, reference_name=GRCm38) because it's incomplete
INFO:root:Predicted 3 effects for variant Variant(contig=1, start=5098048, ref=A, alt=C, reference_name=GRCm38)
INFO:root:Keeping 3/3 non-synonymous coding effects for Variant(contig=1, start=5098048, ref=A, alt=C, reference_name=GRCm38)
INFO:root:Keeping 3/3 effects with predictable AA sequences for Variant(contig=1, start=5098048, ref=A, alt=C, reference_name=GRCm38)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/isovar-protein-sequences.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/script/isovar-protein-sequences.py", line 115, in <module>
    min_mapping_quality=args.min_mapping_quality)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/protein_sequence.py", line 250, in variants_to_protein_sequences_dataframe
    for (variant, protein_sequences) in variants_to_protein_sequences(*args, **kwargs):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/protein_sequence.py", line 194, in variants_to_protein_sequences
    min_mapping_quality=min_mapping_quality):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/translation.py", line 614, in translate_variants
    transcript_id_whitelist=transcript_id_whitelist)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/reference_context.py", line 367, in reference_contexts_for_variant
    context_size=context_size)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/reference_context.py", line 253, in sequence_key_with_reading_frame_for_variant_on_transcript
    context_size=context_size)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/reference_context.py", line 147, in sequence_key_for_variant_on_transcript
    transcript=transcript)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/variant_helpers.py", line 148, in interbase_range_affected_by_variant_on_transcript
    if variant.is_insertion:
AttributeError: 'Variant' object has no attribute 'is_insertion'
```

However, in this case there is clearly a point variant at the locus.

**Comment by iskandr** [comment]
Hey John,

Recently added those to Varcode (https://github.com/hammerlab/varcode/pull/138), try updating?

**Comment by JPFinnigan** [comment]
Done. Corrected that issue. Now seeing:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/isovar-protein-sequences.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/script/isovar-protein-sequences.py", line 115, in <module>
    min_mapping_quality=args.min_mapping_quality)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/protein_sequence.py", line 250, in variants_to_protein_sequences_dataframe
    for (variant, protein_sequences) in variants_to_protein_sequences(*args, **kwargs):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/protein_sequence.py", line 199, in variants_to_protein_sequences
    translations = list(translations)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/translation.py", line 525, in translation_generator
    protein_sequence_length=protein_sequence_length)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/translation.py", line 425, in translate_variant_sequence
    reference_context=reference_context)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/translation.py", line 265, in determine_reading_frame_for_variant_sequence
    cdna_sequence = DNA.concat([cdna_prefix, cdna_alt, cdna_suffix])
AttributeError: type object 'DNA' has no attribute 'concat'
```

**Comment by iskandr** [comment]
Weird. I'm guessing that's an older version of skbio, since I'm using this function:

http://biocore.github.io/scikit-bio/docs/0.4.2/generated/skbio.sequence.DNA.concat.html

**Comment by iskandr** [comment]
I updated the dependencies to be varcode >= 0.4.6 and scikit-bio >= 0.4.2, hopefully that prevents these two errors for other users. 

Let me know whatever the next thing is that goes wrong!

**Comment by JPFinnigan** [comment]
Perfect. Works like a charm. 

Unrelated question is there a way to specify that isovar run in a multi-threaded mode?

**Comment by iskandr** [comment]
Not yet, trying to iron out all the bugs and improve the logic (e.g. using
partial overlaps) before fixing the slowness.
