### ISSUE TITLE
Wrong cDNA sequence after variant for negative strand transcripts (also affecting counts)

### ISSUE THREAD

**Issue by iskandr** [hammerlab/isovar#19]
From @JPFinnigan:

> I’m seeing isovar output ‘supporting_variant_reads’ that grossly differ from the counts in IGV. Also the translated protein sequence is frequently, but not always wrong, particularly when ‘ends_with_stop_codon’ is true.
...
>Ok, so I think I might have figured out the problem. The cdna_sequence preceeding the variant nucleotide comes from the + strand of relative to the mRNA but the cdna_sequence after the variant nucleotide comes aligns to the negative strand (e.g is the reverse compliment) of the mRNA. This portion of the cdna_sequence downstream of the variant (I think you’re calling this the suffix) is the reverse-compliment of the portion upstream of the variant (prefix).
...
>It seems to be a pervasive issue for variants in transcripts from the negative strand...Transcripts on the positive strand are essentially all reconstructed perfectly
...
>Similarly, the supporting_variant_reads counts for variant transcripts on the positive strand are consistent with the counts in IGV (+/- some number that could be explained by filtering). Whereas the supporting_variant_reads counts for variant transcripts on the negative strand are ~2x (+/- some number that could be explained by filtering) the IGV counts which leads me to believe that some fraction of the reads are being counted twice.

**Comment by iskandr** [comment]
Leaving this open until I add unit tests.

**Comment by JPFinnigan** [comment]
Hey, so the last PR fixed essentially all of the errors I was seeing w/ isovar. The supporting read counts are still a little wonky and can range from 0.5-2x the value visible in IGV (I can understand values less than 1x IGV, but I'm not sure how to interpret instances in which the counts are higher than IGV). 

Some interesting edge cases I encountered while spot-checking variants:
chr18:36683093A>C, Stop read-through. Do you think this should be interpreted as "frameshift==TRUE"
chr14:29973444G>A, SNV, occurs after a Stop. Technically a non-coding variant? Does this get annotated by varcode downstream of isovar? 
chr18:73781052A>C, False Positive, Variant _would_ introduce a TAG stop codon if it were present, but there is no support for the variant in the RNA. 

I'll keep looking around, but all of the peptides we synthesized were reconstructed properly. I also have to run w/ the strelka.vcf to see how indels are handled. Otherwise, this looks really good.

**Comment by iskandr** [comment]
>chr18:36683093A>C, Stop read-through. Do you think this should be interpreted as "frameshift==TRUE"

I think we should have a distinct `stoploss` column rather than calling it a frameshift.

**Comment by iskandr** [comment]
>chr14:29973444G>A, SNV, occurs after a Stop. Technically a non-coding variant? Does this get annotated by varcode downstream of isovar? 

There might be a different annotated transcript here with a later stop codon. Let's investigate that further?

**Comment by iskandr** [comment]
>chr18:73781052A>C, False Positive, Variant would introduce a TAG stop codon if it were present, but there is no support for the variant in the RNA.

Maybe explained by the difference in reads we see between isovar and IGV?

**Comment by iskandr** [comment]
@JPFinnigan Arun did a little bit of poking around isovar, found a "everything is totally wrong bug". In the processing of fixing that I found a few more places which were also not quite right. We now have a few unit tests where the isovar variant read counts match what Arun gets from IGV. 

Want to try this branch: https://github.com/hammerlab/isovar/pull/21 and see if your read counts look more reasonable?

**Comment by JPFinnigan** [comment]
Sure, NP. Will let you know how it works out. Thanks for digging into this.

**Comment by JPFinnigan** [comment]
Ran the following:
```
isovar-protein-sequences.py \
--vcf ~/Desktop/WD/Results/WES/ISMMS/B16.F10.0810/VCF/Strelka/B16.F10.0810_strelka.passed.somatic.snvs.indels.vcf \
--bam ~/Desktop/WD/Results/RNA/ISMMS/B16.F10.0810/B16.F10.0810.127A/BAM/HISAT2/B16.F10.0810.127A_HISAT2.sorted.bam \
--genome mm10 \
--min-reads 2 \
--protein-sequence-length 25 \
--output ~/Desktop/B16.F10.0810.127A.isovar.strelka.csv
```

Seeing the following:
```
INFO:root:Gathering variant reads for variant Variant(contig='1', start=139429174, ref='A', alt='C', reference_name='GRCm38') (chromosome=1)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/isovar-protein-sequences.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/script/isovar-protein-sequences.py", line 50, in <module>
    df = variants_to_protein_sequences_dataframe_from_args(args)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/cli_helpers.py", line 36, in variants_to_protein_sequences_dataframe_from_args
    min_mapping_quality=args.min_mapping_quality)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/protein_sequence.py", line 250, in variants_to_protein_sequences_dataframe
    for (variant, protein_sequences) in variants_to_protein_sequences(*args, **kwargs):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/protein_sequence.py", line 194, in variants_to_protein_sequences
    min_mapping_quality=min_mapping_quality):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/translation.py", line 590, in translate_variants
    min_mapping_quality=min_mapping_quality):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/variant_sequence.py", line 166, in variant_sequences_generator
    min_mapping_quality=min_mapping_quality):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/variant_read.py", line 320, in variant_reads_generator
    min_mapping_quality=min_mapping_quality)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/variant_read.py", line 256, in gather_reads_for_single_variant
    min_mapping_quality=min_mapping_quality))
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/read_at_locus.py", line 256, in read_at_locus_generator
    min_mapping_quality=min_mapping_quality)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/read_at_locus.py", line 93, in create_read_at_locus_from_pysam_pileup_element
    name))
TypeError: %d format: a number is required, not NoneType
```

The same error occurs on a different variant from a MuTect .vcf:

```
INFO:root:Gathering variant reads for variant Variant(contig='6', start=137837118, ref='T', alt='G', reference_name='GRCm38') (chromosome=6)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/isovar-protein-sequences.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/script/isovar-protein-sequences.py", line 50, in <module>
    df = variants_to_protein_sequences_dataframe_from_args(args)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/cli_helpers.py", line 36, in variants_to_protein_sequences_dataframe_from_args
    min_mapping_quality=args.min_mapping_quality)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/protein_sequence.py", line 250, in variants_to_protein_sequences_dataframe
    for (variant, protein_sequences) in variants_to_protein_sequences(*args, **kwargs):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/protein_sequence.py", line 194, in variants_to_protein_sequences
    min_mapping_quality=min_mapping_quality):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/translation.py", line 590, in translate_variants
    min_mapping_quality=min_mapping_quality):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/variant_sequence.py", line 166, in variant_sequences_generator
    min_mapping_quality=min_mapping_quality):
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/variant_read.py", line 320, in variant_reads_generator
    min_mapping_quality=min_mapping_quality)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/variant_read.py", line 256, in gather_reads_for_single_variant
    min_mapping_quality=min_mapping_quality))
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/read_at_locus.py", line 256, in read_at_locus_generator
    min_mapping_quality=min_mapping_quality)
  File "/Users/johnfinnigan/Desktop/Utilities/Isovar/isovar/isovar/read_at_locus.py", line 93, in create_read_at_locus_from_pysam_pileup_element
    name))
TypeError: %d format: a number is required, not NoneType
```

The Strelka variant is a SNV immediately adjacent to a deletion which is present in both RNASeq sets. The Mutect variant is a SNV w/in 3nt of a splice junction. All 3 variants are in all B16.F1 and B16.F10 WES and RNAseq.

**Comment by iskandr** [comment]
Hey @JPFinnigan, sorry about that, it was a small bug in some debug printing. I'll add these variants as test cases. Want to try pulling the most recent version?

**Comment by iskandr** [comment]
Not sure exactly when this got fixed but recent versions have had counts that match manual inspection. @JPFinnigan have you had any problems with the newest isovar?
