### ISSUE TITLE
Error running isovar-variant-sequences.py

### ISSUE THREAD

**Issue by iskandr** [hammerlab/isovar#52]
> $isovar-variant-sequences.py --vcf mutect.vcf --vcf strelka.vcf --bam tumor-rna.bam --output-csv isovar-variant-sequences.csv
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.4/bin/isovar-variant-sequences.py", line 6, in <module>
>     exec(compile(open(__file__).read(), __file__, 'exec'))
>   File "/Users/iskander/code/isovar/script/isovar-variant-sequences.py", line 28, in <module>
>     logging.config.fileConfig(pkg_resources.resource_filename(__name__, 'logging.conf'))
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/config.py", line 76, in fileConfig
>     formatters = _create_formatters(cp)
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/config.py", line 109, in _create_formatters
>     flist = cp["formatters"]["keys"]
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/configparser.py", line 937, in __getitem__
>     raise KeyError(key)
> KeyError: 'formatters'

**Comment by iskandr** [comment]
Currently working around this by commenting out this line: 
```# logging.config.fileConfig(pkg_resources.resource_filename("isovar", 'logging.conf'))```

The only down-side is not seeing any logging statements.
