### ISSUE TITLE
ValueError: Reference genome 'hg19' not found

### ISSUE THREAD

**Issue by ggrimes** [hammerlab/isovar#62]
I am getting the error  " Reference genome 'hg19' not found "  when I run the command

isovar-protein-sequences.py \
 --vcf my.vcf \
--bam accepted_hits.bam  \
--genome hg19

Traceback (most recent call last):
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/bin/isovar-protein-sequences.py", line 4, in <module>
    __import__('pkg_resources').run_script('isovar==0.3.1', 'isovar-protein-sequences.py')
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/lib/python2.7/site-packages/isovar-0.3.1-py2.7.egg/EGG-INFO/scripts/isovar-protein-sequences.py", line 46, in <module>

  File "build/bdist.linux-x86_64/egg/isovar/cli/protein_sequences.py", line 70, in protein_sequences_dataframe_from_args
  File "build/bdist.linux-x86_64/egg/isovar/cli/protein_sequences.py", line 60, in protein_sequences_generator_from_args
  File "build/bdist.linux-x86_64/egg/isovar/cli/rna_reads.py", line 79, in allele_reads_generator_from_args
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/lib/python2.7/site-packages/varcode-0.5.10-py2.7.egg/varcode/cli/variant_args.py", line 101, in variant_collection_from_args
    genome = genome_for_reference_name(args.genome)
  File "build/bdist.linux-x86_64/egg/pyensembl/__init__.py", line 51, in genome_for_reference_name
  File "build/bdist.linux-x86_64/egg/pyensembl/species.py", line 138, in normalize_reference_name
ValueError: Reference genome 'hg19' not found

Any ideas what has gone wrong?

Thanks,

Graeme

**Comment by iskandr** [comment]
Hi Graeme, 

Unfortunately, we never added proper support for hg19 to PyEnsembl. It's part of a longer-term plan for that library but in other cases we have, so far, been faking support by using GRCh37 and dropping mitochondrial variants. You can do the same thing in this case by passing 'grch37' as the genome, but I acknowledge that it's a band-aid solution at best!

There are two routes to actually support hg19: continue using Ensembl gene annotations but patch in the older mitochondrial sequence/genes used by hg19. Alternatively, we can generalize PyEnsembl to also support RefSeq gene annotations. I'm guessing the latter is what you're interested in but it's worth checking just to be sure. 

--Alex

**Comment by iskandr** [comment]
Also, if you drop `--genome hg19` then our variant parsing/annotation library will automatically fall back on GRCh37 for you, though it does not yet drop the mitochondrial variants.

**Comment by iskandr** [comment]
Ah, just noticed we're using that genome in our README example. Just removed it. @ggrimes were you able to get isovar working without the `--genome` flag?

**Comment by ggrimes** [comment]
I get the following message when I run it without a genome 
"build/bdist.linux-x86_64/egg/pyensembl/download_cache.py"

ValueError: Missing genome data file from ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/pep/Homo_sapiens.GRCh37.75.pep.all.fa.gz. Run pyensembl install --release 75 --species homo_sapiens

when I  Run pyensembl install --release 75 --species homo_sapiens I get the following error

pyensembl install --release 75 --species homo_sapiens
2016-11-21 09:10:48,739 - pyensembl.shell - INFO - Running 'install' for EnsemblRelease(release=75, species='homo_sapiens')
2016-11-21 09:10:48,740 - pyensembl.database - INFO - Creating database: /home/ggrimes2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.gtf.db
2016-11-21 09:10:48,740 - pyensembl.gtf - INFO - Reading GTF from /home/ggrimes2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.gtf.gz
2016-11-21 09:10:48,749 - pyensembl.gtf - INFO - Creating missing gene features...
Traceback (most recent call last):
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/bin/pyensembl", line 9, in <module>
    load_entry_point('pyensembl==1.0.3', 'console_scripts', 'pyensembl')()
  File "build/bdist.linux-x86_64/egg/pyensembl/shell.py", line 156, in run
  File "build/bdist.linux-x86_64/egg/pyensembl/genome.py", line 230, in index
  File "build/bdist.linux-x86_64/egg/pyensembl/database.py", line 261, in connect_or_create
  File "build/bdist.linux-x86_64/egg/pyensembl/database.py", line 192, in create
  File "build/bdist.linux-x86_64/egg/pyensembl/gtf.py", line 249, in dataframe
  File "build/bdist.linux-x86_64/egg/pyensembl/gtf.py", line 213, in _construct_df
  File "build/bdist.linux-x86_64/egg/pyensembl/gtf.py", line 133, in _load_full_dataframe_cached
  File "build/bdist.linux-x86_64/egg/pyensembl/memory_cache.py", line 107, in cached_dataframe
  File "build/bdist.linux-x86_64/egg/pyensembl/gtf.py", line 167, in _load_full_dataframe_from_gtf
  File "build/bdist.linux-x86_64/egg/gtfparse/create_missing_features.py", line 67, in create_missing_features
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/lib/python2.7/site-packages/pandas/core/frame.py", line 1914, in __getitem__
    return self._getitem_column(key)
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/lib/python2.7/site-packages/pandas/core/frame.py", line 1921, in _getitem_column
    return self._get_item_cache(key)
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/lib/python2.7/site-packages/pandas/core/generic.py", line 1090, in _get_item_cache
    values = self._data.get(item)
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/lib/python2.7/site-packages/pandas/core/internals.py", line 3102, in get
    loc = self.items.get_loc(item)
  File "/exports/igmm/software/pkg/el7/apps/python/2.7.10/lib/python2.7/site-packages/pandas/core/index.py", line 1692, in get_loc
    return self._engine.get_loc(_values_from_object(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:3979)
  File "pandas/index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas/index.c:3843)
  File "pandas/hashtable.pyx", line 668, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12265)
  File "pandas/hashtable.pyx", line 676, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12216)
KeyError: 'gene_id'

Any ideas what is going wrong?

Thanks

**Comment by iskandr** [comment]
Run: pyensembl install --release 75 --species homo_sapiens

**Comment by iskandr** [comment]
@ggrimes That's unexpected! Any chance that `/home/ggrimes2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.gtf.gz` is empty? Can you paste the first few lines of that file here?

**Comment by ggrimes** [comment]
Yes, the file was empty . I deleted it and re-ran command now everything runs ok.
Thanks for the help.

Graeme
